apiVersion: apps/v1

kind: Deployment

metadata:

  name: java-proj

  labels:

    app: java

spec:

  replicas: 3

  selector:

    matchLabels:

      app: java

  template:

    metadata:

      labels:

        app: java

    spec:

      containers:

      - name: java-proj

        image: javascriptdocker:latest

        ports:

        - containerPort: 8080
